### ISSUE TITLE
How to using your library?

### ISSUE THREAD

**Issue by radoslavius** [goetas-webservices/soap-client#21]
Hi,

I'm trying use your library for source `https://gclient.geis.cz/GService/GService.svc?singlewsdl`, but I don't know if I have configured it incorrectly or source is not good. Can you explain where I can find error?

My config file:
```
soap_client:

  namespaces:
    'http://tempuri.org/': 'Soap/GeisClient'
  destinations_php:
    'Geis/Client': src/soap
  destinations_jms:
    'Geis/Client': src/soap/metadata

  metadata:
    'https://gclient.geis.cz/GService/GService.svc?singlewsdl': ~
```

Command which I run
```
 vendor/goetas-webservices/soap-client/bin/soap-client generate \
 soap_config.yml \
 --dest-class=Soap/GeisClient \
 src/soap
```

The result is this error:
```
In SchemaReader.php line 597:
Can't find type named {http://schemas.datacontract.org/2004/07/GService.Manager}#RequestOfServiceRequestHUsxwOXq, at line 1 in https://gclient.geis.cz/GService/GService.svc?singlewsdl  
In Schema.php line 248:                                                                                                                         
Can't find the Type named {http://schemas.datacontract.org/2004/07/GService.Manager}#RequestOfServiceRequestHUsxwOXq.                                                                                                                         
```

Thanks
